name: shaunfox.com
site.name: old shaunfox.com
permalink: /:categories/:title.html
url: https://okshaun.com
paginate_per_category: true
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
baseurl: /shaunrfox-2015
